### ISSUE TITLE
Hello Node.js

### ISSUE THREAD

**Issue by Akiindex** [Akiindex/line-bot-sample#1]
'use strict'

const HTTP = require('http');
const PORT = process.env.PORT || 3001;

HTTP.createServer((req, res) => {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello Node.js !\n');
}).listen(PORT);

No problem.
I used github for the first time, so I misused it.
I want you to correspond quickly to Japanese.

**Comment by anku580** [comment]
Are you facing some issue while executing this code?

**Comment by Akiindex** [comment]
No problem.
I used github for the first time, so I misused it.
I want you to correspond quickly to Japanese.
